Traceback (most recent call last):
  File "./train.py", line 28, in <module>
    opt = TrainOptions().parse()   # get training options
  File "/usr/itetnas04/data-scratch-01/dlim_03hs20/data/DLIM/options/base_options.py", line 115, in parse
    opt = self.gather_options()
  File "/usr/itetnas04/data-scratch-01/dlim_03hs20/data/DLIM/options/base_options.py", line 75, in gather_options
    model_option_setter = models.get_option_setter(model_name)
  File "/usr/itetnas04/data-scratch-01/dlim_03hs20/data/DLIM/models/__init__.py", line 50, in get_option_setter
    model_class = find_model_using_name(model_name)
  File "/usr/itetnas04/data-scratch-01/dlim_03hs20/data/DLIM/models/__init__.py", line 33, in find_model_using_name
    modellib = importlib.import_module(model_filename)
  File "/usr/itetnas04/data-scratch-01/dlim_03hs20/data/conda_envs/machineLearning/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/itetnas04/data-scratch-01/dlim_03hs20/data/DLIM/models/stochastic_model.py", line 4, in <module>
    from . import sesamDis
ImportError: cannot import name 'sesamDis' from 'models' (/usr/itetnas04/data-scratch-01/dlim_03hs20/data/DLIM/models/__init__.py)
Traceback (most recent call last):
  File "./test.py", line 38, in <module>
    opt = TestOptions().parse()  # get test options
  File "/usr/itetnas04/data-scratch-01/dlim_03hs20/data/DLIM/options/base_options.py", line 115, in parse
    opt = self.gather_options()
  File "/usr/itetnas04/data-scratch-01/dlim_03hs20/data/DLIM/options/base_options.py", line 75, in gather_options
    model_option_setter = models.get_option_setter(model_name)
  File "/usr/itetnas04/data-scratch-01/dlim_03hs20/data/DLIM/models/__init__.py", line 50, in get_option_setter
    model_class = find_model_using_name(model_name)
  File "/usr/itetnas04/data-scratch-01/dlim_03hs20/data/DLIM/models/__init__.py", line 33, in find_model_using_name
    modellib = importlib.import_module(model_filename)
  File "/usr/itetnas04/data-scratch-01/dlim_03hs20/data/conda_envs/machineLearning/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/itetnas04/data-scratch-01/dlim_03hs20/data/DLIM/models/stochastic_model.py", line 4, in <module>
    from . import sesamDis
ImportError: cannot import name 'sesamDis' from 'models' (/usr/itetnas04/data-scratch-01/dlim_03hs20/data/DLIM/models/__init__.py)
Creating feature extractor "inception-v3-compat" with features ['2048', 'logits_unbiased']
Traceback (most recent call last):
  File "./nicolasScripts/fidelityStochastic.py", line 10, in <module>
    stoch_metrics = calculate_metrics("./results/stoch/test_latest/images/", "./datasets/facades/test/", cuda=False, isc=True, fid=True, kid=False, verbose=True)
  File "/usr/itetnas04/data-scratch-01/dlim_03hs20/data/conda_envs/fidelitySupport/lib/python3.8/site-packages/torch_fidelity/metrics.py", line 118, in calculate_metrics
    cacheable_input1_name = get_input_cacheable_name(input_1, get_kwarg('cache_input1_name', kwargs))
  File "/usr/itetnas04/data-scratch-01/dlim_03hs20/data/conda_envs/fidelitySupport/lib/python3.8/site-packages/torch_fidelity/utils.py", line 118, in get_input_cacheable_name
    raise ValueError(f'Unknown format of input string "{input}"')
ValueError: Unknown format of input string "./results/stoch/test_latest/images/"
